name: mlops-ex6

on:
  push:

jobs:
  run:
    runs-on: windows-latest  # ✅ Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker on Windows
        run: |
          choco install docker-cli

      - name: Pull Existing Docker Image
        run: |
          docker pull vaisnave/exp_5

      - name: Run Docker Container
        run: |
          docker run -d --name exp_5 -p 8000:8000 vaisnave/exp_5
