name: mlops-ex6

on:
  push:

jobs:
  run:
    runs-on: windows-latest  # Use Windows runner instead of Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker on Windows Runner
        run: |
          choco install docker-cli

      - name: Pull Existing Docker Image
        run: |
          docker pull vaisnave/exp_5

      - name: Run Docker Container
        run: |
          docker run --rm --name exp_5 vaisnave/exp_5
